Description: >
    Jonathan Garrels, 2020
    This template deploys the server infrastructure for the Udagram web app.

Parameters:
    EnvironmentName:
        Description: The environment name that will be prefixed to resource names.
        Type: String

    ImageID:
        Description: The EC2 AMI ID.
        Type: String

    InstanceType:
        Description: The EC2 instance type for the web servers.
        Type: String


Resources:
    LoadBalancerSecurityGroup:
        Type: AWS::EC2:SecurityGroup
        Properties:
            GroupDescription: Allow http traffic to the Load Balancer.
            VpcId:
                Fn::ImportValue:
                    !Sub "${EnvironmentName}-VPC"
            SecurityGroupIngress:
            - IpProtocol: tcp
              FromPort: 80
              ToPort: 80
              CidrIp: 0.0.0.0/0
            SecurityGroupEgress:
            - IpProtocol: tcp
              FromPort: 80
              ToPort: 80
              CidrIp: 0.0.0.0/0

    WebServerSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties: 
            GroupDescription: Allow http to the web servers.
            VpcId:
                Fn::ImportValue:
                    !Sub "${EnvironmentName}-VPC"
            SecurityGroupIngress:
                - IpProtocol: tcp
                  FromPort: 80
                  ToPort: 80
                  CidrIp: 0.0.0.0/0
            SecurityGroupEgress:
                - IpProtocol: tcp
                  FromPort: 80
                  ToPort: 80
                  CidrIp: 0.0.0.0/0

    WebAppLaunchConfig:
        Type: AWS::AutoScaling::LaunchConfiguration
        Properties:
            UserData:
                Fn::Base64: !Sub |
                    #!/bin/bash
                    apt-get update -y
                    apt-get install unzip awscli -<
                    apt-get install apache2 -y
                    systemctl start apache2.service
                    cd /var/www/html
                    aws s3 cp s3://udacity-demo-1/udacity.zip .
                    unzip -o udacity.zip
            ImageId: !Ref ImageID
            InstanceType: !Ref InstanceType
            SecurityGroups: !Ref WebServerSecurityGroup
            IamInstanceProfile: !Ref S3ListReadProfile
            BlockDeviceMappings:
            - DeviceName: "/dev/sdk"
              Ebs:
                VolumeSize: "10"

    WebAppAutoScalingGroup:
        Type: AWS::AutoScaling::AutoScalingGroup
        Properties:
            VPCZoneIdentifier:
            - Fn::ImportValue:
                !Sub "${EnvironmentName}-VPC"
            LaunchConfigurationName: !Ref WebAppLaunchConfig
            MinSize: "1"
            MaxSize: "1"
            TargetGroupARNs:
            - !Ref ALBTargetGroup

    ApplicationLoadBalancer:
        Type: AWS::ElasticLoadBalancingV2::LoadBalancer
        Properties:
            Scheme: internet-facing
            Subnets:
            - Fn::ImportValue: !Sub "${EnvironmentName}-PUBLIC-SUBNET-1"
            - Fn::ImportValue: !Sub "${EnvironmentName}-PUBLIC-SUBNET-2"
            SecurityGroups:
            - !Ref LoadBalancerSecurityGroup
            Type: application

    ALBListener:
        Type: AWS::ElasticLoadBalancingV2::Listener
        Properties:
            DefaultActions:
            - Type: forward
              TargetGrouopArn: !Ref ALBTargetGroup
            LoadBalancerARN: !Ref ApplicationLoadBalancer
            Port: 80
            Protocol: HTTP

    ALBListenerRule:
        Type: AWS::ElasticLoadBalancingV2::ListenerRule
        Properties:
            Actions:
            - Type: forward
              TargetGroupArn: !Ref ALBTargetGroup
            Conditions:
            - Field: path-pattern
              Values: [/]
            ListenerArn: !Ref ALBListener

    ALBTargetGroup:
        Type: AWS::ElasticLoadBalancingV2::TargetGroup
        Properties:
            HealthCheckIntervalSeconds: 60
            HealthCheckPath: /
            HealthCheckProtocol: HTTP
            HealthCheckTimeoutSeconds: 10
            HealthCheckThresholdCount: 3
            Port: 80
            UnhealthyThresholdCount: 5
            VpcId:
                Fn::ImportValue:
                    !Sub "${EnvironmentName}-VPC"

    S3ListReadProfile:
        Type: AWS::IAM::InstanceProfile
        Properties:
            Roles:
            - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        


Outputs:
    LoadBalancerURL:
        Description: The DNS name of the application load balancer.
        Value:
            Fn::Join:
                - ''
                - - http://
                  - !GetAtt ApplicationLoadBalancer.DNSName

