Description: >
    Jonathan Garrels, 2020
    This template deploys the server infrastructure for the Udagram web app.

Parameters:
    EnvironmentName:
        Description: The environment name that will be prefixed to resource names.
        Type: String


Resources:
    LoadBalancerSecurityGroup:
        Type: AWS::EC2:SecurityGroup
        Properties:
            GroupDescription: Allow http traffic to the Load Balancer.
            VpcId:
                FN::ImportValue:
                    !Sub "${EnvironmentName}-VPC"
            SecurityGroupIngress:
            - IpProtocol: tcp
              FromPort: 80
              ToPort: 80
              CidrIp: 0.0.0.0/0
            SecurityGroupEgress:
            - IpProtocol: tcp
              FromPort: 80
              ToPort: 80
              CidrIp: 0.0.0.0/0

    WebServerSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties: 
            GroupDescription: Allow http to the web servers.
            VpcId:
                Fn::ImportValue:
                    !Sub "${EnvironmentName}-VPC"
            SecurityGroupIngress:
                - IpProtocol: tcp
                  FromPort: 80
                  ToPort: 80
                  CidrIp: 0.0.0.0/0
            SecurityGroupEgress:
                - IpProtocol: tcp
                  FromPort: 80
                  ToPort: 80
                  CidrIp: 0.0.0.0/0

    WebAppLaunchConfig:

    WebAppAutoScalingGroup:

    ApplicationLoadBalancer:

    ALBListener:

    ALBListenerRule:

    ALBTargetGroup:

    S3ListReadRole:
        


Outputs:
    LoadBalancerURL:

